version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-cidade_saude_db}
      POSTGRES_USER: ${DB_USER:-cidade_user}
      POSTGRES_PASSWORD: ${DB_PASS:-cidade_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-cidade_saude_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-cidade_user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS:-cidade_pass}
      SERVER_PORT: ${SPRING_PORT:-5011}
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "${SPRING_PORT:-5011}:${SPRING_PORT:-5011}"
    depends_on:
      - db

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:5011}
    depends_on:
      - backend

volumes:
  postgres_data:
