#!/bin/bash

echo "========================================"
echo "   Push FINAL para feature/intellij-ai"
echo "========================================"
echo ""
echo "Este script vai enviar TODOS os commits para feature/intellij-ai"
echo ""
echo "Commits que serão enviados:"
echo "- 3ccdf98 Merge branch claude into feature/intellij-ai"
echo "- 9fb8f79 Remove corrupted file with invalid path"
echo "- aca6388 Merge improvements"
echo "- a47469e Restore GlobalExceptionHandler.java"
echo "- 67640c2 Add security configuration templates"
echo "- f3ce040 Add PR documentation"
echo "- 538bbd8 Implement Nursing Care Module"
echo "- 6ea6051 Security improvements"
echo "- b4c05ad Organize files"
echo "- 7e5ba32 Fix code quality"
echo "- 628723d Fix security issues"
echo "- b26b717 Add codebase analysis"
echo ""
echo "Total: 14 commits"
echo ""
read -p "Pressione ENTER para continuar..."

cd "$(dirname "$0")"

echo ""
echo "Executando: git push origin feature/intellij-ai"
echo ""

git push origin feature/intellij-ai

if [ $? -eq 0 ]; then
    echo ""
    echo "========================================"
    echo "   ✅ PUSH REALIZADO COM SUCESSO!"
    echo "========================================"
    echo ""
    echo "Todas as melhorias foram enviadas:"
    echo "✅ Módulo de Enfermagem completo"
    echo "✅ Sistema de Auditoria"
    echo "✅ Rate Limiting"
    echo "✅ 12 Exception Handlers"
    echo "✅ Templates de Segurança"
    echo "✅ Documentação completa"
    echo "✅ Arquivo corrompido removido"
    echo ""
else
    echo ""
    echo "========================================"
    echo "   ❌ ERRO AO FAZER PUSH"
    echo "========================================"
    echo ""
    echo "Verifique:"
    echo "1. Conexão com a internet"
    echo "2. Permissões no GitHub"
    echo "3. Token de autenticação"
    echo ""
    echo "Tente executar manualmente:"
    echo "git push origin feature/intellij-ai"
    echo ""
fi
